### ISSUE TITLE
Question: Should we use NPM_AUTH_TOKEN if it is set?

### ISSUE THREAD

**Issue by JakeChampion** [Financial-Times/origami-ci-tools#13]
Currently we throw an error if `NPM_TOKEN` is not set, I've seen most automated npm publishing workflows at the FT use `NPM_AUTH_TOKEN`.

Should we make origami-ci-tools use either environment variable if they are set? If both environment variables are set and contain different values, what should we do?

**Comment by rowanmanning** [comment]
I like the idea of supporting both environment variables. I think I prefer `NPM_AUTH_TOKEN` as it's more explicit so possibly output a warning that multiple keys are set but default to that one?

**Comment by chee** [comment]
I don't know, we have a documented API and we didn't build this tool for Customer Products.

Printing an error if they haven't set the documented variable seems better in my opinion, but I'm not against accepting both. But if we accept both then we need to add an error message if they are different.
