### ISSUE TITLE
Run pa11y against all supported brands

### ISSUE THREAD

**Issue by notlee** [Financial-Times/origami-ci-tools#23]
origami-ci-tools [builds the pa11y demo](https://github.com/Financial-Times/origami-ci-tools/blob/a2364ce76750ba6f963dd28e84da57dbec34b9cb/commands/branch.js#L15) for the master brand only. 

This means we are not running pa11y against the internal version of components. 
If a component [like o-meter](https://github.com/Financial-Times/o-meter/issues/2) is internal brand only the command fails. 

Why haven't we seen this error before you ask? [o-layout](https://github.com/Financial-Times/o-layout) is our only other internal brand component but it has no pa11y demo.

**Comment by chee** [comment]
how does one run `pa11y` against the other brands with obt?

**Comment by notlee** [comment]
`obt test` runts `pa11y` against the demo named `pa11y`. To run against different brands, in its current form, we'd have to rebuild the `pa11y` demo for that brand using the `demo` command with the`brand` flag e.g. `obt demo --demo-filter=pa11y --brand=internal && obt test`

**Comment by notlee** [comment]
Instead `obt test` could build the `pa11y` demo for each brand in a temporary directory, and run `pa11y` against each of them. Removing the need to run `obt demo` first.

It would be slower but maybe we shouldn't even have a `pa11y` specific demo... we could run `pa11y` against all our demos.

**Comment by notlee** [comment]
Jake says:
>The reason we stopped running pa11y against all demos was because it made the markup in the demos contain lots of extra attributes that were distracting from what the demo was meant to be showing

We can still have, optionally, an extra pa11y demo which is hidden from the registry, and still have pa11y run on all other demos. 

Note worthy: I've seen since removed [hover and other state](https://github.com/Financial-Times/o-buttons/commit/c13ee74abfa4d2731410ce16eb6d17499feccf1a#diff-bf0fb135efa69a14d71d3a973a919ad5L5) classes in the pa11y demo for o-buttons. They've been removed though -- either to reduce the bundle size or o-buttons, or to remove the complexity of a pa11y demo variable to add extra classes for testing.
